### ISSUE TITLE
main is broken: crates/dst/tests/custodian.rs calls reconcile_step with stale arity (E0061)

### ISSUE THREAD

**Issue by eduralph** [getwyrd/wyrd#211]
## Problem

`main` does not compile. `cargo xtask ci` fails building the `wyrd-dst` `custodian` test target:

```
error[E0061]: this function takes 7 arguments but 6 arguments were supplied
   --> crates/dst/tests/custodian.rs:522 (and 574, 616, 664, 686, 812, 889, 905, 916, 951, 974)
note: function defined here --> crates/custodian/src/reconciliation.rs:65
```

## Root cause

A merge-order semantic conflict (clean to git, broken to the compiler):

- **#193** (M3-7 rebalance/drain/decommission) inserted a 6th parameter `rebalance: Option<&RebalanceContext<'_>>` into `reconcile_step`, pushing `now_millis` to the 7th position.
- **#194** (M3-8 DST custodian campaign) added `crates/dst/tests/custodian.rs` written against the older **6-arg** signature, and was merged without rebasing onto #193.

Both merged without textual conflict, leaving `main` red.

## Fix

`crates/dst/tests/custodian.rs` uses **no** `RebalanceContext` (only a doc-comment mention) — all 11 calls are rebalance-agnostic. Insert `None` in the new `rebalance` slot (immediately before the trailing timestamp argument) in each of the 11 calls. This preserves each test's original intent exactly. The tests that actually exercise the rebalance loop live in `crates/custodian/tests/rebalance.rs` and are unaffected.

This blocks every PR's `rust`/`gate` checks (e.g. #210) until fixed.
